### ISSUE TITLE
[00001] Template compilation error: calculate_softplus_body called with 1 template parameter but signature requires 2 (missing is_fp32_dest_acc_en). This is a deterministic compile-time error introduced by PR #42115.

### ISSUE THREAD

**Issue by ebanerjeeTT** [tenstorrent/tt-auto-triage#1153]
**Number of Occurrences:** 1

## Error Message

```
Template compilation error: calculate_softplus_body called with 1 template parameter but signature requires 2 (missing is_fp32_dest_acc_en). This is a deterministic compile-time error introduced by PR #42115.
```

## All Occurrences
This error has occurred 1 time(s):

1. [[CENTROID] April 16th, 6:32am, 15.36 seconds](https://github.com/tenstorrent/tt-metal/actions/runs/24492939989/job/71582119666) - blackhole-demo-tests / blackhole-demo-tests (DeskBox (2xP150), cloud-mlperf, 2, bh_deskbox) / llama3.1-8b performance batch-1 (commit: 9d4ab66ebb3d446bc78da9ac09d4d2e4fe220522)

    ```
    Template compilation error: calculate_softplus_body called with 1 template parameter but signature requires 2 (missing is_fp32_dest_acc_en). This is a deterministic compile-time error introduced by PR #42115.
    ```

**Comment by ebanerjeeTT** [comment]
Closing as stale — no activity in 30+ days. This appears to be an auto-generated CI triage ticket; reopen if it's still relevant or actively being tracked.
