### ISSUE TITLE
[00001] Compilation error: '_calculate_fill_' is not a member of 'ckernel::sfpu' in mul_reduce_scalar.h:81. This is caused by commit 3ef40fe1 (LLK header refactoring batch 3) which removed the transitive include of sfpu/ckernel_sfpu_fill.h from...

### ISSUE THREAD

**Issue by ebanerjeeTT** [tenstorrent/tt-auto-triage#1229]
**Number of Occurrences:** 1

## Error Message

```
Compilation error: '_calculate_fill_' is not a member of 'ckernel::sfpu' in mul_reduce_scalar.h:81. This is caused by commit 3ef40fe1 (LLK header refactoring batch 3) which removed the transitive include of sfpu/ckernel_sfpu_fill.h from ckernel_sfpu.h. The file mul_reduce_scalar.h uses _calculate_fill_ but does not explicitly include the required header.
```

## All Occurrences
This error has occurred 1 time(s):

1. [[CENTROID] April 19th, 1:10pm, 31.84 seconds](https://github.com/tenstorrent/tt-metal/actions/runs/24628671845/job/72012410798) - blackhole-post-commit / ops-unit-tests (P150b) / blackhole deepseek blitz op tests (fast dispatch) blackhole P150b (commit: 60e857ac2ce8e199e618b9df23c0a9349ebad320)

    ```
    Compilation error: '_calculate_fill_' is not a member of 'ckernel::sfpu' in mul_reduce_scalar.h:81. This is caused by commit 3ef40fe1 (LLK header refactoring batch 3) which removed the transitive include of sfpu/ckernel_sfpu_fill.h from ckernel_sfpu.h. The file mul_reduce_scalar.h uses _calculate_fill_ but does not explicitly include the required header.
    ```

**Comment by ebanerjeeTT** [comment]
Closing as stale — no activity in 30+ days. This appears to be an auto-generated CI triage ticket; reopen if it's still relevant or actively being tracked.
